### ISSUE TITLE
Errors in samples, How to change route in "See it in Action?"

### ISSUE THREAD

**Issue by davidchrest** [afang/hyperlapse.js#4] opened 2016-03-01 02:46 UTC
Hi Andy,
Lover that you have this. I would really like to have this on a web site, however, your **simple.html** example comes up as a blank page with many of these errors: "Image from origin 'http://maps.google.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 400."

Your **viewer.html** example has a map, pins, viewer window, and controls but nothing seems to work. The pins jump around and do not stay where I put them. There is this error: "Uncaught TypeError: Cannot read property 'pano_id' of undefined."

I exported your "**See it in action**" example from http://codepen.io/afang/pen/GpxqLQ. I see in your code you have origin and destination coordinates along a straight section of road. How does one incorporate multiple turns?

I'd love to get something the viewer.html working where I could just drop points and generate the hyperlapse.

Am I doing something wrong? Any help is incredibly appreciated.

David

**Comment by afang** [comment] 2016-03-03 04:05
Duplicate of #3

**Closed by afang** 2016-03-03 04:05 UTC
